version: '3'

services:
  app:
    container_name: app
    build: ./docker/phalcon
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/phalcon/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/phalcon/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: phalcon_app
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

#Docker Networks
networks:
  app-network:
    driver: bridge
